{% set name = "arabica" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arabica-{{ version }}.tar.gz
  sha256: cd2c62aa907f6a91aa65bfb850c6a5e94cea6dfb881820c0a0ea29799dfb4e5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas ==1.4.0
    - nltk ==3.6.2
    - regex ==2022.10.31
    - finvader ==1.0.4
    - matplotlib-base ==3.6.0
    - matplotlib-inline ==0.1.6
    - plotnine ==0.10.1
    - wordcloud ==1.9.3
    - jenkspy ==0.3.2
    - vadersentiment ==3.3.2
    - cleantext ==1.1.4
    - mizani ==0.9.2
    - pillow ==9.4.0
    - ftfy >=6.2.0
    - chardet ==5.2.0

test:
  imports:
    - arabica
  # Removing pip check due to wordcloud failing to report proper version
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  #   - pip

about:
  home: https://github.com/PetrKorab/Arabica
  doc_url: https://arabica.readthedocs.io/
  summary: Python package for exploratory text data analysis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
